import { strict as assert } from 'assert';
import { Vertex, VertexState } from "./base/graph";
import { Tree, Node } from "web-tree-sitter";
import crypto from 'crypto';
import Path from 'path';
import fs from 'fs';

let mod_counter = 0;

function uniqueSN(): string {
    const id = mod_counter.toString();
    ++mod_counter;
    return id;
}

export type Symbol  = string;
export type ModID   = string;
export type ModPath = string;

export enum ModuleState {
    NORMAL,
    OUT_OF_DATE,
}
export class Module implements Vertex {
    public _m_state: ModuleState;
    public state: VertexState = VertexState.UNDISCOVERED;

    public _mtimeMs: number = 0;

    public static overrides: Map<ModID, Symbol[]> = new Map();
    public static override_list: Symbol[] = [];

    private _circular_point: Module[] = [];

    // Autogenerated global unique identifier for each Module.
    private _ident: ModID;

    private _sn: string;
    private _path: string;
    private _tree: Tree;
    private _deps: Module[]   = [];
    private _depBys: Module[] = [];

    private _maybe_external_symbol_list: Symbol[] | null = null;
    private _external_symbols: Map<ModID,Symbol[]> = new Map();

    // Global Symbols
    private _func_symbols: Symbol[] = [];
    private _var_symbols: Symbol[] = [];
    private _type_symbols: Symbol[] = [];

    public equal(mod: Module) {
        return this._ident == mod._ident &&
            this._mtimeMs == mod._mtimeMs;
    }

    public destruct() {
        this._m_state = ModuleState.OUT_OF_DATE;

        if (Module.overrides.has(this._ident)) {
            const overrides = Module.overrides.get(this._ident) as Symbol[];
            Module.override_list =
                Module.override_list.filter((sym: Symbol) => {
                    return overrides.find(
                        (sym_in_this_module: Symbol) => {
                            return sym_in_this_module == sym;
                        }) == undefined;
                });
            Module.overrides.delete(this._ident);
        }
    }

    public get circular_point() {
        return this._circular_point;
    }

    public addCircularPoint(mod: Module) {
        this._circular_point.push(mod);
    }

    public get func_syms(): Symbol[] {
        return this._func_symbols;
    }

    public addFuncSym(s: Symbol) {
        this._func_symbols.push(s);
    }

    public get var_syms(): Symbol[] {
        return this._var_symbols;
    }

    public addVarSym(s: Symbol) {
        this._var_symbols.push(s);
    }

    public get type_syms(): Symbol[] {
        return this._type_symbols;
    }

    public addTypeSym(s: Symbol) {
        this._type_symbols.push(s);
    }

    public get edges() {
        return this._deps;
    }

    public get tree() {
        return this._tree;
    }

    constructor(path: ModPath, tree: Tree) {
        this._m_state = ModuleState.NORMAL;

        this._path = Path.resolve(path);
        assert(fs.existsSync(this._path));

        this._tree = tree;
        this._sn = uniqueSN();

        this._ident = Module.getIdentByPath(this._path);
    }

    public static async build(path: ModPath, tree: Tree) {
        let m = new Module(path, tree);
        m._mtimeMs = (await fs.promises.stat(path)).mtimeMs;
        return m;
    }

    public static getIdentByPath(path: string): string {
        path = Path.resolve(path);
        const hash = crypto.createHash('sha256');
        hash.update(path, 'utf8');
        return hash.digest('base64');
    }

    public async isOutOfDate(): Promise<boolean> {
        if (this._m_state == ModuleState.OUT_OF_DATE) {
            return true;
        }
        const current_mtimeMs = (await fs.promises.stat(this._path)).mtimeMs;
        return current_mtimeMs > this._mtimeMs;
    }

    public setExternalSymbols(id: ModID, symbols: Symbol[]) {
        this._external_symbols.set(id, symbols);
        this._maybe_external_symbol_list = null;
    }

    public getExternalSymbols(id: ModID): Symbol[] | undefined {
        return this._external_symbols.get(id);
    }

    public get allExternalSymbols() {
        if (this._maybe_external_symbol_list == null) {
            this._maybe_external_symbol_list =
                Array.from(this._external_symbols.values()).reduce(
                    (acc,cur) => {
                        return acc.concat(cur);
                    },
                    []);
        }
        return this._maybe_external_symbol_list;
    }

    public get ident() {
        return this._ident;
    }

    public get sn() {
        return this._sn;
    }

    public get rootNode(): Node {
        return this._tree.rootNode;
    }

    public isDepOn(may_dep: Module) {
        return this._deps.find((m: Module) => {
            return may_dep.path == m.path;
        }) != undefined;
    }

    public isDepBy(may_dep_by: Module) {
        return may_dep_by.isDepOn(this);
    }

    public getAllDepBy() {
        return this._depBys;
    }

    public dep(m: Module) {
        this._deps.push(m);
    }
    public getDep(ident: ModID) {
        return this._deps.find((m: Module) => {
            m.ident == ident;
        });
    }
    public removeDep(ident: ModID) {
        this._deps = this._deps.filter((m: Module) => {
            return m.ident != ident;
        });
    }
    public depBy(m: Module) {
        this._depBys.push(m);
    }
    public getDepBy(ident: ModID) {
        return this._depBys.find((m: Module) => {
            return m.ident == ident;
        });
    }
    public removeDepBy(ident: ModID) {
        this._depBys = this._depBys.filter((m: Module) => {
            return m.ident != ident;
        });
    }

    public get path() {
        return this._path;
    }

    public isExternalSymbol(sym: Symbol) {
        return this.allExternalSymbols.find(
            (s) => s == sym) != undefined;
    }

    public symbolFrom(sym: Symbol): ModID | null {
        let maybe_mod_id =
            Array.from(this._external_symbols.keys()).find((key) => {
                return (this._external_symbols.get(key) as string[])
                    .find((s) => s == sym) != undefined; });
        if (maybe_mod_id == undefined) {
            return null;
        } else {
            return maybe_mod_id;
        }
    }
}
